server:
  port: 9094

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      routes:

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: auth-service-admin
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/admin/**

        - id: auth-service-seller
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/seller/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:mysecurekeymysecurekeymysecurekey123456}
